### ISSUE TITLE
error while attempting to install

### ISSUE THREAD

**Issue by gilbertohasnofb** [orklann/atom-spotify3#1]
I tried installing this package on my Linux Mint 64-bit machine but got the following output:

```
npm ERR! Linux 4.13.0-45-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/gilberto/.atom/.apm/.apmrc" "--userconfig" "/home/gilberto/.atom/.apmrc" "install" "/tmp/d-118102-19113-12no1k2.6tqot21emi/package.tgz" "--runtime=electron" "--target=2.0.3" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for atom-spotify3@0.3.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118102-19113-1kq7jjz.aifxzb0529/npm-debug.log

```

**Comment by orklann** [comment]
Sorry for the inconvenience, this package is not working at the moment. Please try `atom-spotify2`

https://atom.io/packages/atom-spotify2

And AFAIK, `atom-spotify2` require atom running on macOS. Linux is not supported yet.

**Comment by gilbertohasnofb** [comment]
Thanks for the quick reply. I did check `atom-spotify2` and the author does say it's a OS X only package. Do you have any plans of perhaps adding Linux compatibility at some point in your fork?

**Comment by orklann** [comment]
Not at the moment, I am using a modified version of `atom-spotify2` on my Mac. I don't know if the Linux version of Spotify support the same function as the Mac version so that other apps can access the current playing track info, and can also control Spotify.

**Comment by gilbertohasnofb** [comment]
Many thanks for the replies. If you ever feel like adding Linux compatibility, I would be happy to test it over here.
